### ISSUE TITLE
ObservableList<T> does not implement IReadOnlyList<T>

### ISSUE THREAD

**Issue by wojciechsura** [gsonnenf/Gstc.Collections.ObservableLists#4]
`ObservableList<T>` derives from `AbstractUpcastList<T>`, which implements `IList<T>`, but does not implement `IReadOnlyList<T>`.

I think this fix should be trivial as `IReadOnlyList<T>` is actually a subset of `IList<T>`. Can you please implement this small fix?

**Comment by gsonnenf** [comment]
Ah yes, this is some strange behavior. I had expected it to just work, as `IReadOnlyList<T>` is inherited from `IList<T>`  and their are implementations of the  `IReadOnlyList<T>` methods. 

but, I ran a unit test on it.  And sure enough, Roslyn didn't flag it as an invalid cast, but in runtime it threw an InvalidCastException().

I've added `IReadOnlyList<T>` to both the `AbstractUpcastList<T>' and the `ObservableList<T>` along with explicit implementations of `IReadOnlyList<T>` and it still fails to cast. 

Any idea what might be causing this?

**Comment by gsonnenf** [comment]
Ah, my mistake. It turns out `IList<T>` does not inherit `IReadOnlyList<T>` as I previously thought. I'll see what I can do about fixing this. The unit test is working correctly now.

**Comment by gsonnenf** [comment]
`IReadOnlyList<T>` is added to the interface of `IObservableList<T>`,  `AbstractUpcastList<T>`, and `AbstractUpcastLockingList<T>`. It should be available in the Dev2.0.1 branch with this commit:

https://github.com/gsonnenf/Gstc.Collections.ObservableLists/tree/09acbefe63a1aa35a59698d4b457c5e0cf6d5564

I'm currently working on a release version of ObservableDictionary, and its pointed to a few places I can improve ObservableList (which it uses). I have a few more bug/features queued and should be creating a release version 2.0.1 of this library in a week or two.
