### ISSUE TITLE
ObservableList throws when using IndexOf(object) with incompatible type

### ISSUE THREAD

**Issue by edoust** [gsonnenf/Gstc.Collections.ObservableLists#6]
When using the `IList.IndexOf(Object)` method on `ObservableList<T>` with an incompatible type, an exception is thrown. This happens when using the observable list as `ItemsSource` for a WinUI `TabView` control

The `List<T>` implementation checks for type compatibility and returns `-1` in case the type is not castable to the generic type parameter `T` - see the [reference source](https://referencesource.microsoft.com/#mscorlib/system/collections/generic/list.cs,618)

Since in the above mentioned scenario the calls to `ObservableList<T>` can't be changed, and this terminates the app, I would appreciate it if this could be fixed

**Comment by gsonnenf** [comment]
Ah yes. Let me get this fixed. It I'll go ahead and put the fix in the dev2.0.1 branch.

**Comment by gsonnenf** [comment]
Issue resolved. `ObservableList<TItem>`,  `ObservableIList<TItem,TList>`,  `ObservableIListLocking<TItem,TList>` should now behave similarly to a `List<T>` that is cast to `IList`. Please see the following commit:

https://github.com/gsonnenf/Gstc.Collections.ObservableLists/tree/c77d607db02af0b7f3c56a5b4f76f96182b9243c

A couple unit test were added to verify this functionality: [Gstc.Collections.ObservableLists.Test/ObservableListUpcastTest.cs](https://github.com/gsonnenf/Gstc.Collections.ObservableLists/commit/c77d607db02af0b7f3c56a5b4f76f96182b9243c#diff-841f09763c161cb90fd9336e0d540670d1ac5a40d4981a490656b7bba78ffc25)

IList functionality was also added back to ObservableIListLocking, a workaround was added for internal lists that do not add items to the end of this list, and quite a few other changes were also made. See the change log here: https://github.com/gsonnenf/Gstc.Collections.ObservableLists/commit/c77d607db02af0b7f3c56a5b4f76f96182b9243c
